const seed = [
  {id:1,date:'2026-09-09',origin:'GRU',destination:'LIS',type:'round',travelers:1,price:1847},
  {id:2,date:'2026-09-09',origin:'GRU',destination:'LIS',type:'outbound',travelers:1,price:1120},
  {id:3,date:'2026-09-09',origin:'GRU',destination:'LIS',type:'round',travelers:2,price:3980},
  {id:4,date:'2026-09-08',origin:'GRU',destination:'LIS',type:'return',travelers:1,price:1280},
  {id:5,date:'2026-09-07',origin:'GRU',destination:'LIS',type:'round',travelers:1,price:2190},
  {id:6,date:'2026-09-06',origin:'GRU',destination:'LIS',type:'outbound',travelers:2,price:2440},
  {id:7,date:'2026-09-05',origin:'GRU',destination:'LIS',type:'round',travelers:1,price:2280},
  {id:8,date:'2026-09-04',origin:'GRU',destination:'LIS',type:'return',travelers:1,price:1390},
  {id:9,date:'2026-09-03',origin:'GRU',destination:'LIS',type:'round',travelers:2,price:4680},
  {id:10,date:'2026-09-02',origin:'GRU',destination:'LIS',type:'round',travelers:1,price:2390},
  {id:11,date:'2026-09-01',origin:'GRU',destination:'LIS',type:'outbound',travelers:1,price:1340},
  {id:12,date:'2026-08-31',origin:'GRU',destination:'LIS',type:'round',travelers:1,price:2490}
];
const key='rota-certa-searches-v1';
let records=JSON.parse(localStorage.getItem(key)||'null')||seed;
let visible=5;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v);
const labels={round:'Ida e volta',outbound:'Só ida',return:'Só volta'};
const formatDate=value=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)).replace('.','');
function status(record){const unit=record.price/record.travelers;const peers=records.filter(r=>r.type===record.type).map(r=>r.price/r.travelers);const avg=peers.reduce((a,b)=>a+b,0)/peers.length;if(unit<avg*.88)return['Melhor preço','best'];if(unit>avg*1.12)return['Preço alto','high'];return['Na média','average']}
function render(){
  const query=document.querySelector('#search-input').value.toUpperCase();const type=document.querySelector('#trip-filter').value;
  const filtered=records.filter(r=>(type==='all'||r.type===type)&&(`${r.origin} ${r.destination}`.includes(query))).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);
  const body=document.querySelector('#history-body');body.innerHTML=filtered.slice(0,visible).map(r=>{const s=status(r);return `<tr><td>${formatDate(r.date)}</td><td><span class="route">${r.origin}<span class="plane">✈</span>${r.destination}</span></td><td><span class="type-badge ${r.type}">${labels[r.type]}</span></td><td>${r.travelers} ${r.travelers===1?'pessoa':'pessoas'}</td><td><strong>${money(r.price)}</strong></td><td>${money(r.price/r.travelers)}</td><td><span class="status-badge ${s[1]}">${s[0]}</span></td><td><button class="delete-button" data-id="${r.id}" aria-label="Excluir">⋮</button></td></tr>`}).join('');
  document.querySelector('#empty-state').hidden=filtered.length>0;document.querySelector('#results-label').textContent=`Mostrando ${Math.min(visible,filtered.length)} de ${filtered.length} pesquisas`;document.querySelector('#load-more').hidden=visible>=filtered.length;
  const round=records.filter(r=>r.type==='round');const lowest=round.reduce((best,r)=>(r.price/r.travelers)<(best.price/best.travelers)?r:best,round[0]||records[0]);
  if(lowest){document.querySelector('#lowest-price').textContent=money(lowest.price/lowest.travelers);document.querySelector('#lowest-detail').textContent=`${labels[lowest.type]} · ${lowest.travelers} ${lowest.travelers===1?'pessoa':'pessoas'}`}
  const recent=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7);document.querySelector('#average-price').textContent=money(recent.reduce((a,r)=>a+r.price/r.travelers,0)/recent.length);document.querySelector('#search-count').textContent=records.length;document.querySelector('#today-count').textContent=`${records.filter(r=>r.date===new Date().toISOString().slice(0,10)).length} adicionadas hoje`;drawChart();
}
function drawChart(){const svg=document.querySelector('#price-chart'),w=700,h=205,p={l:46,r:15,t:14,b:28};svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const days=['03 set','04 set','05 set','06 set','07 set','08 set','Hoje'];const series=[{c:'#0c827d',v:[2390,2320,2280,2210,2190,2070,1847]},{c:'#e77d69',v:[1380,1350,1320,1280,1250,1190,1120]},{c:'#173435',v:[1460,1390,1420,1340,1320,1280,1240]}];const min=900,max=2600,x=i=>p.l+i*(w-p.l-p.r)/6,y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min);let html='';[1000,1500,2000,2500].forEach(v=>{html+=`<line x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}" stroke="#e6eae5" stroke-dasharray="3 4"/><text x="0" y="${y(v)+4}" font-size="9" fill="#899793">R$ ${String(v/1000).replace('.',',')}k</text>`});days.forEach((d,i)=>html+=`<text x="${x(i)}" y="${h-5}" text-anchor="middle" font-size="9" fill="#899793">${d}</text>`);series.forEach((s,si)=>{const pts=s.v.map((v,i)=>`${x(i)},${y(v)}`).join(' ');html+=`<polyline points="${pts}" fill="none" stroke="${s.c}" stroke-width="${si===0?3:2}" stroke-linecap="round" stroke-linejoin="round"/>`;s.v.forEach((v,i)=>html+=`<circle cx="${x(i)}" cy="${y(v)}" r="${si===0?3:2.2}" fill="#fff" stroke="${s.c}" stroke-width="2"/>`)});svg.innerHTML=html}
const dialog=document.querySelector('#entry-dialog'),form=document.querySelector('#entry-form');document.querySelector('#open-form').onclick=()=>{form.date.value=new Date().toISOString().slice(0,10);dialog.showModal()};['close-form','cancel-form'].forEach(id=>document.querySelector(`#${id}`).onclick=()=>dialog.close());form.onsubmit=e=>{e.preventDefault();const data=new FormData(form);records.unshift({id:Date.now(),date:data.get('date'),origin:data.get('origin').toUpperCase(),destination:data.get('destination').toUpperCase(),type:data.get('type'),travelers:Number(data.get('travelers')),price:Number(data.get('price'))});localStorage.setItem(key,JSON.stringify(records));form.reset();dialog.close();render();const toast=document.querySelector('#toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)};
document.querySelector('#history-body').onclick=e=>{const button=e.target.closest('.delete-button');if(button&&confirm('Excluir esta pesquisa?')){records=records.filter(r=>r.id!==Number(button.dataset.id));localStorage.setItem(key,JSON.stringify(records));render()}};['search-input','trip-filter'].forEach(id=>document.querySelector(`#${id}`).addEventListener(id==='search-input'?'input':'change',()=>{visible=5;render()}));document.querySelector('#load-more').onclick=()=>{visible+=5;render()};document.querySelector('#show-best').onclick=()=>document.querySelector('.history-panel').scrollIntoView({behavior:'smooth'});render();
